name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --with dev

  unit-test:
    name: Unit tests execution
    runs-on: ubuntu-latest
    needs:
      - install-dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'poetry'

      - name: Run Tests with Coverage
        run: |
          poetry run coverage run --source=src -m pytest tests/unit
          poetry run coverage report
          poetry run coverage xml -i

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-unit
          path: coverage.xml

  integration-test:
    name: Integration tests execution
    runs-on: ubuntu-latest
    needs:
      - install-dependencies
      - unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'poetry'

      - name: Run Tests with Coverage
        run: |
          poetry run coverage run --source=src -m pytest tests/it
          poetry run coverage report
          poetry run coverage xml -i

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-it
          path: coverage.xml

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: [unit-test, integration-test]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Download coverage reports
        uses: actions/download-artifact@v4

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}