name: Static code analysis

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--line-length 120"
          src: src

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'poetry'

      - name: Install mypy
        run: mypy src

  architecture:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install import-linter
        run: pip install import-linter

      - name: Run linter
        run: lint-imports

  security_checks:
    runs-on: ubuntu-latest
    name: Execute the pycharm-security action
    steps:
      - uses: actions/checkout@v3
      - name: Run PyCharm Security
        uses: tonybaloney/pycharm-security@master

      - name: Prepare pythone env
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install import-linter
        run: pip install bandit

      - name: Run bandit analysis
        run: bandit -r src/

